Introduction
============

This guide will walk you through installing and starting up JBoss Application Server 7. It will then introduce key features of the Java EE 6 (Web Profile) programming model, of which JBoss AS 7 is a certified implementation.


[TIP]
.Java EE 6
========================================================================
The Java EE 6 platform offers developers the ability to write 
distributed, transactional and portable applications quickly and easily. 
We class applications that require these capabilities "enterprise 
applications". These applications must be fast, secure and reliable.

Java EE has always offered strong messaging (JMS), transactional (JTA) 
and resource (JCA) capabilities as well as exposing web services via 
SOAP (JAX-WS). Java EE 5 started a radical shift for the programming 
model, offering a powerful, declarative and lightweight 
object-relational mapper (JPA) and  annotation-driven, lightweight 
access to enterprise services (EJB 3). Java EE 6 added a type-safe, 
loosely coupled programming model (CDI), declarative validation of 
constraints (Bean Validation) and RESTful web services (JAX-RS) to 
produce a complete, modern development environment.
========================================================================


JBoss AS 7 departs from the familiar structure of previous JBoss AS versions, so we recommend all developers follow the steps in xref:getting_started_with_jboss_as[] to install and start up the application server for the first time. 

JBoss AS 7 comes with a series of quickstarts aimed to get you up to writing applications with minimal fuss. We recommend that start by working through the quickstarts in this guide, in the order they are presented. Of you have previous experience with Java EE 6, you may wish to skip some or all of the quickstarts.

[options="header"]
|========================================================================
|Core                           | 
| xref:helloworld_quickstart[]  | If you have previously developed applications using technologies such as JSF or Wicket, and EJB or Spring, you may wish to skip this quickstart.
| xref:numberguess_quickstart[] | If you have previously developed applications using technologies such as JSF or Wicket, EJB or Spring, and JPA or Hibernate you may wish to skip this quickstart.
| xref:greeter_quickstart[]     | If you are a Java EE wizard you may wish to skip this quickstart.
| xref:kitchensink_quickstart[] | A great starting point for your project.
|Optional                       | 
| xref:osgi_quickstart[]        | If you want to get started with OSGi in JBoss AS, check out this quickstart.
|========================================================================


Downloading the quickstarts
---------------------------

The quickstarts are are available for download from link:http://www.jboss.org/jdf/quickstarts/jboss-as-quickstart[JBoss Developer Framework]. Make sure you download the latest zip! 

